In [1]:
import numpy as np

### np.ones, np.zeros and np.append

In [2]:
np.ones(3)  # 1D array

array([1., 1., 1.])

In [3]:
np.zeros(3)  # 1D array

array([0., 0., 0.])

In [4]:
np.append(np.ones(3), np.zeros(3))  # 1D

array([1., 1., 1., 0., 0., 0.])

In [5]:
np.ones((3, 1))  # 2D: 3 rows and 1 column

array([[1.],
       [1.],
       [1.]])

In [6]:
np.zeros((3, 1))  # 2D: 3 rows and 1 column

array([[0.],
       [0.],
       [0.]])

In [7]:
np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=None)  # 1D even that inside is 2D and axis=None is a default

array([1., 1., 1., 0., 0., 0.])

In [8]:
np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=0)  # 2D: 6 rows and 1 column if axis=0

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [9]:
res = np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=1) # with axis=1, need have the same size. Ex. (3, 1) and (3, 1)
res

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

In [10]:
res.shape

(3, 2)

### np.squeeze()

In [11]:
ones = np.ones((3, 1))
ones  # 2D: 3 rows, 1 column

array([[1.],
       [1.],
       [1.]])

In [12]:
np.squeeze(ones) # change 2D --> 1D numpy array

array([1., 1., 1.])

In [13]:
np.squeeze(ones).tolist() # change 2D --> 1D numpy array --> Python list

[1.0, 1.0, 1.0]

### np.dot: matrix multiplication

In [14]:
a = np.array([[1, 0], [0, 1]])  # Identity matrix
a

array([[1, 0],
       [0, 1]])

In [15]:
b = np.array([[4, 1], [2, 2]])
b

array([[4, 1],
       [2, 2]])

In [16]:
np.dot(a, b) # for 2D array, the same as matmul or a @ b

array([[4, 1],
       [2, 2]])

In [17]:
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [18]:
a @ b   # both a and b must be 2D numpy array

array([[4, 1],
       [2, 2]])

### np.exp, np.log (natural log), np.log10, np.log2

In [19]:
np.log(100)  

4.605170185988092

### Calculate accuracy

In [20]:
y_label = np.array([1.0, 0.0, 0.0])  # target label 
y_hat =   np.array([1.0, 0.0, 1.0])  # target prediction

correct = y_hat == y_label
correct

array([ True,  True, False])

In [21]:
accuracy = correct.sum()/correct.size
accuracy

0.6666666666666666

In [22]:
25*40/13

76.92307692307692

### (Python)  Note to get value from key of python dict

In [23]:
dic = {'aa': 10, 'bb': 'test'}
v = dic.get('aa', 0)
v

10

In [24]:
v = dic.get('ccc', 0)
v

0

### Relu by numpy. Relu = max(x, 0)

In [29]:
a1 = np.array([[1, -1,0], [-10, 1, 5]])  
a1

array([[  1,  -1,   0],
       [-10,   1,   5]])

#### method 1

In [30]:
a1[a1 < 0] = 0
a1

array([[1, 0, 0],
       [0, 1, 5]])

#### method 2

In [33]:
a1 = np.array([[1, -1,0], [-10, 1, 5]]) 
np.maximum(a1, 0)

array([[1, 0, 0],
       [0, 1, 5]])

### np.ones_like()

In [32]:
a2 = np.ones_like(a1)  # make a2 is matrix with size=size of a1 and all values=1
a2

array([[1, 1, 1],
       [1, 1, 1]])