In [1]:
import numpy as np

### np.ones, np.zeros and np.append

In [2]:
np.ones(3)  # 1D array

array([1., 1., 1.])

In [3]:
np.zeros(3)  # 1D array

array([0., 0., 0.])

In [4]:
np.append(np.ones(3), np.zeros(3))  # 1D

array([1., 1., 1., 0., 0., 0.])

In [5]:
np.ones((3, 1))  # 2D: 3 rows and 1 column

array([[1.],
       [1.],
       [1.]])

In [6]:
np.zeros((3, 1))  # 2D: 3 rows and 1 column

array([[0.],
       [0.],
       [0.]])

In [7]:
np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=None)  # 1D even that inside is 2D and axis=None is a default

array([1., 1., 1., 0., 0., 0.])

In [8]:
np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=0)  # 2D: 6 rows and 1 column if axis=0

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [9]:
np.append(np.ones((3, 1)), np.zeros((3, 1)), axis=1) # with axis=1, need have the same size. Ex. (3, 1) and (3, 1)

array([[1., 0.],
       [1., 0.],
       [1., 0.]])